development:
  adapter: postgresql
  encoding: unicode
  database: tps_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tps_test
  pool: 5
  username: postgres
  password:
  host: localhost
